### ISSUE TITLE
Bouton annuler la Typographie ne marche pas

### ISSUE THREAD

**Issue by thomas37000** [thomas37000/SynApi#5]
Quand on clique sur le bouton annuler pour revenir à la Typographie par défault ARIAL rien ne ce passe.
que ça soit en storage / json ou front la typographie reste à l' ancien state selectionné / l' ancienne typo 
 Donc ne marche pas ?

**Comment by FredHasselot** [comment]
Tu devrais faire l'inverse de la fonction qui change de font. Pour commencer. (et ensuite tu pouurras optimiser ça)

par exemple : 

```
const restoreFontFamily = (selectedFont) => {
    setActiveFontFamily('Arial'); // Remet la police par default (pourrait etre une variable a gérer d'un seul endroit.)
    states.function.restoreFontFamily(); // appel la fonction restoreFontFamily du context
    sessionStorage.setItem('font_family', 'Arial'); // Met à jour le storage
  }; 
```

que tu appellerais comme ça : 

```<BtnCancel handleClick={() => restoreFontFamily()} />```

Note l'arrow function. 
Sans arrow function, tu lances la fonction directement. sans interaction.

Vu que tu as une fonction qui ajoute un font et une autre qui remet a zero tu pourrais certainement n'avoir qu'une seule fonction pour faire les deux. Du genre toggle.

`ToggleFontFamily(ICI_UN_PARAMETRE)` par exemple. 
Si c'est "Add" ou true en paramètre ou la condition que tu définies -> boum c'est un ajout sinon (else) -> c'est un reset.

Mais tu peux déjà faire ce que j'ai noté au dessus.
Pour comprendre comment ça marche. 
Comme pour "handleChangeFontFamily" on a trois opérations dans "restoreFontFamily": 

1. On remet la police par default (Arial) dans le state local (du composant)
2. On fait la même chose dans le context.
3. On met a jour le storage.

Tout ça pourrait s’écrire autrement ET être optimisé également.
Mais déjà ça, ça va fonctionner.

**Comment by thomas37000** [comment]
super merci, j' ai enlevé states.function.restoreFontFamily(); 
car ça faisait planté au click sur submit
